export default {
    foreground: '#292929',
    background: '#fff',
    'widget.shadow': 'transparent',
    //titleBar
    'titleBar.activeForeground': '#292929',
    'titleBar.activeBackground': '#ffffff',
    'titleBar.border': '#0f4a85',
    'menubar.selectionForeground': '#292929',
    'menubar.selectionBackground': 'transparent',
    'menubar.selectionBorder': '#0f4a85',
    //menu
    'menu.foreground': '#292929',
    'menu.background': '#fff',
    'menu.border': '#0f4a85',
    'menu.selectionForeground': '#0f4a85',
    'menu.selectionBackground': 'transparent',
    'menu.selectionBorder': '#0f4a85',
    'menu.separatorBackground': '#0f4a85',
    //statusBar
    'statusBar.foreground': '#292929',
    'statusBar.background': '#fff',
    'statusBar.border': '#0f4a85',
    'statusBarItem.hoverBackground': 'transparent',
    'statusBarItem.activeBackground': 'transparent',
    //sideBar
    'sideBar.foreground': '#292929',
    'sideBar.background': '#fff',
    'sideBar.border': '#0f4a85',
    'sideBarTitle.foreground': '#292929',
    // list
    'list.activeSelectionForeground': '#0f4a85',
    'list.activeSelectionBackground': 'transparent',
    'list.focusForeground': '#292929',
    'list.focusBackground': 'transparent',
    'list.focusOutline': '#0f4a85',
    'list.hoverForeground': '#292929',
    'list.hoverBackground': 'rgba(0, 0, 0, 0.12)',
    // dropdown
    'dropdown-foreground': '#292929',
    'dropdown-background': '#fff',
    'dropdown-border': '#0f4a85',
    // tab
    'editorGroupHeader.tabsBackground': '#fff',
    'editorGroupHeader.border': '#0f4a85',
    'tab.border': '#0f4a85',
    'tab.activeForeground': '#292929',
    'tab.activeBackground': '#fff',
    'tab.inactiveForeground': '#292929',
    'tab.inactiveBackground': '#fff',
    'tab.activeBorder': 'transparent',
    'tab.activeBorderTop': '#b5200d',
    'tab.hoverForeground': '#292929',
    'tab.hoverBackground': '#fff',
    'tab.hoverBorder': '#0f4a85',
    // editor
    'editor.foreground': '#292929',
    'editor.background': '#fff',
    'editorLineNumber.foreground': '#292929',
    'editorLineNumber.activeForeground': '#000',
    'editorCursor.foreground': '#292929',
    'editor.selectionForeground': '#fff',
    'editor.selectionBackground': '#0f4a85',
    'editor.selectionHighlightBorder': '#0f4a85',
    'editor.selectionHighlightBackground': 'transparent',
    'editor.findMatchBackground': '#0f4a85',
    'editor.findMatchBorder': 'transparent',
    'editor.findMatchHighlightBackground': 'transparent',
    'editor.findMatchHighlightBorder': '#0f4a85',
    'editor.lineHighlightBackground': 'transparent',
    'editor.lineHighlightBorder': '#0f4a85',
    'editorIndentGuide.background': '',
    'editorIndentGuide.activeBackground': '',
    'editorWhitespace.foreground': 'rgba(0, 0, 0, 0.2)',
    // editorWidget
    'editorWidget.foreground': '#292929',
    'editorWidget.background': '#fff',
    'editorWidget.border': '#0f4a85',
    'editorSuggestWidget.foreground': '#292929',
    'editorSuggestWidget.background': '#fff',
    'editorSuggestWidget.border': '#0f4a85',
    'editorSuggestWidget.selectedForeground': '#0f4a85',
    'editorSuggestWidget.selectedBackground': '#fff',
    'editorSuggestWidget.highlightForeground': '#0f4a85',
    'editorSuggestWidget.focusHighlightForeground': '#0f4a85',
    // input
    'input.foreground': '#292929',
    'input.background': '#fff',
    'input.border': '#0f4a85',
    'input.placeholderForeground': '#999',
    'inputOption.activeForeground': '#0f4a85',
    'inputOption.activeBackground': '#fff',
    'inputOption.activeBorder': '#0f4a85',
    'inputOption.hoverBackground': 'rgba(0, 0, 0, 0.2)',
    // toolbar
    'toolbar.hoverBackground': 'rgba(0, 0, 0, 0.2)',
    'toolbar.activeBackground': 'transparent',
    'toolbar.hoverOutline': '#0f4a85',
};
