export default {
    foreground: '#ccc',
    background: 'rgba(60,60,60)',
    'widget.shadow': 'rgba(0,0,0,0.36)',
    //titleBar
    'titlebar.activeForeground': '#ccc',
    'titleBar.activeBackground': 'rgba(60,60,60)',
    'titleBar.border': 'transparent',
    'menubar.selectionForeground': '#ccc',
    'menubar.selectionBackground': 'rgba(200, 200, 200, 0.4)',
    'menubar.selectionBorder': 'transparent',
    //menu
    'menu.foreground': '#ccc',
    'menu.background': 'rgb(37,37,38)',
    'menu.border': 'transparent',
    'menu.selectionForeground': '#fff',
    'menu.selectionBackground': '#0066b8',
    'menu.selectionBorder': 'transparent',
    'menu.separatorBackground': 'rgba(200, 200, 200, 0.4)',
    //statusBar
    'statusBar.foreground': '#ccc',
    'statusBar.background': 'rgba(60,60,60)',
    'statusBar.border': 'transparent',
    'statusBarItem.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    'statusBarItem.activeBackground': 'rgba(200, 200, 200, 0.4)',
    //sideBar
    'sideBar.foreground': '#ccc',
    'sideBar.background': 'rgba(37,37,38)',
    'sideBar.border': 'transparent',
    'sideBarTitle.foreground': '#ccc',
    // list
    'list.activeSelectionForeground': '#fff',
    'list.activeSelectionBackground': '#0066b8',
    'list.focusForeground': '#ccc',
    'list.focusBackground': 'transparent',
    'list.focusOutline': '#0066b8',
    'list.hoverForeground': '#ccc',
    'list.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    // tab
    'editorGroupHeader.tabsBackground': 'rgb(37,37,38)',
    'editorGroupHeader.border': 'transparent',
    'tab.border': 'transparent',
    'tab.activeForeground': '#fff',
    'tab.activeBackground': '',
    'tab.inactiveForeground': '#ccc',
    'tab.inactiveBackground': 'transparent',
    'tab.activeBorder': 'transparent',
    'tab.activeBorderTop': 'transparent',
    'tab.hoverForeground': '#fff',
    'tab.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    'tab.hoverBorder': 'transparent',
    // editor
    'editor.foreground': '#ccc',
    'editor.background': 'rgb(30,30,30)',
    'editorLineNumber.foreground': 'rgb(120,120,120)',
    'editorLineNumber.activeForeground': '#fff',
    'editorCursor.foreground': '#fff',
    'editor.selectionForeground': '#ccc',
    'editor.selectionBackground': '#0097fb6e',
    'editor.selectionHighlightBorder': '#0098fb',
    'editor.selectionHighlightBackground': 'transparent',
    'editor.findMatchBackground': 'rgb(250, 201, 171)',
    'editor.findMatchBorder': 'transparent',
    'editor.findMatchHighlightBackground': 'transparent',
    'editor.findMatchHighlightBorder': '#0098fb',
    'editor.lineHighlightBackground': 'transparent',
    'editor.lineHighlightBorder': 'rgba(200, 200, 200, 0.4)',
    // editorWidget
    'editorWidget.foreground': '#ccc',
    'editorWidget.background': 'rgb(37,37,38)',
    'editorWidget.border': 'transparent',
    'editorSuggestWidget.foreground': '#ccc',
    'editorSuggestWidget.background': 'rgb(37,37,38)',
    'editorSuggestWidget.border': 'transparent',
    'editorSuggestWidget.selectedForeground': '#ccc',
    'editorSuggestWidget.selectedBackground': '#0098fb',
    'editorSuggestWidget.highlightForeground': '#0098fb',
    'editorSuggestWidget.focusHighlightForeground': '#fff',
    // input
    'input.foreground': '#ccc',
    'input.background': 'rgb(60,60,60)',
    'input.border': '#0098fb',
    'input.placeholderForeground': '#999',
    'inputOption.activeForeground': '#ccc',
    'inputOption.activeBackground': 'rgb(204, 233, 252)',
    'inputOption.activeBorder': 'transparent',
    'inputOption.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    // toolbar
    'toolbar.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    'toolbar.activeBackground': 'transparent',
    'toolbar.hoverOutline': 'transparent',
};
