export default {
    foreground: '#575757',
    background: '#fff',
    'widget.shadow': 'rgba(0,0,0,0.16)',
    //titleBar
    'titlebar.activeForeground': '#575757',
    'titleBar.activeBackground': '#ddd',
    'titleBar.border': 'transparent',
    'menubar.selectionForeground': '#575757',
    'menubar.selectionBackground': 'rgba(200, 200, 200, 0.4)',
    'menubar.selectionBorder': 'transparent',
    //menu
    'menu.foreground': '#575757',
    'menu.background': '#fff',
    'menu.border': 'rgba(200, 200, 200, 0.4)',
    'menu.selectionForeground': '#fff',
    'menu.selectionBackground': '#0066b8',
    'menu.selectionBorder': 'transparent',
    'menu.separatorBackground': 'rgba(200, 200, 200, 0.4)',
    //statusBar
    'statusBar.foreground': '#575757',
    'statusBar.background': '#ddd',
    'statusBar.border': 'transparent',
    'statusBarItem.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    'statusBarItem.activeBackground': 'rgba(200, 200, 200, 0.4)',
    //sideBar
    'sideBar.foreground': '#575757',
    'sideBar.background': '#eee',
    'sideBar.border': '#ddd',
    'sideBarTitle.foreground': '#575757',
    // list
    'list.activeSelectionForeground': '#fff',
    'list.activeSelectionBackground': '#0066b8',
    'list.focusForeground': '#575757',
    'list.focusBackground': 'transparent',
    'list.focusOutline': '#0066b8',
    'list.hoverForeground': '#575757',
    'list.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    // tab
    'editorGroupHeader.tabsBackground': '#eee',
    'editorGroupHeader.border': 'transparent',
    'tab.border': 'transparent',
    'tab.activeForeground': '#333',
    'tab.activeBackground': 'transparent',
    'tab.inactiveForeground': '#575757',
    'tab.inactiveBackground': 'transparent',
    'tab.activeBorder': 'transparent',
    'tab.activeBorderTop': 'transparent',
    'tab.hoverForeground': '#333',
    'tab.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    'tab.hoverBorder': 'transparent',
    // editor
    'editor.foreground': '#575757',
    'editor.background': '#fff',
    'editorLineNumber.foreground': '#999',
    'editorLineNumber.activeForeground': '#333',
    'editorCursor.foreground': '#333',
    'editor.selectionForeground': '#575757',
    'editor.selectionBackground': '#0097fb6e',
    'editor.selectionHighlightBorder': '#0098fb',
    'editor.selectionHighlightBackground': 'transparent',
    'editor.findMatchBackground': 'rgb(250, 201, 171)',
    'editor.findMatchBorder': 'transparent',
    'editor.findMatchHighlightBackground': 'transparent',
    'editor.findMatchHighlightBorder': '#0098fb',
    'editor.lineHighlightBackground': 'transparent',
    'editor.lineHighlightBorder': 'rgba(200, 200, 200, 0.4)',
    // editorWidget
    'editorWidget.foreground': '#575757',
    'editorWidget.background': '#eee',
    'editorWidget.border': '#ddd',
    'editorSuggestWidget.foreground': '#575757',
    'editorSuggestWidget.background': '#eee',
    'editorSuggestWidget.border': '#ddd',
    'editorSuggestWidget.selectedForeground': '#575757',
    'editorSuggestWidget.selectedBackground': '#0098fb',
    'editorSuggestWidget.highlightForeground': '#0098fb',
    'editorSuggestWidget.focusHighlightForeground': '#fff',
    // input
    'input.foreground': '#575757',
    'input.background': '#fff',
    'input.border': '#0098fb',
    'input.placeholderForeground': '#999',
    'inputOption.activeForeground': '#575757',
    'inputOption.activeBackground': 'rgb(204, 233, 252)',
    'inputOption.activeBorder': 'transparent',
    'inputOption.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    // toolbar
    'toolbar.hoverBackground': 'rgba(200, 200, 200, 0.4)',
    'toolbar.activeBackground': 'transparent',
    'toolbar.hoverOutline': 'transparent',
};
